# Generated by Django 6.0 on 2025-12-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transactionhistoryentry_related_payment_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_status_218b80_idx',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
