# Generated by Django 6.0 on 2025-12-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethodref',
            name='provider_customer_id',
        ),
        migrations.RemoveField(
            model_name='paymentmethodref',
            name='provider_payment_method_id',
        ),
        migrations.AddField(
            model_name='paymentmethodref',
            name='stripe_payment_method_id',
            field=models.CharField(default='pm_default', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethodref',
            name='provider',
            field=models.CharField(choices=[('fake', 'Fake Gateway'), ('yoomoney', 'YooMoney')], default='fake', max_length=20),
        ),
    ]
